blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://github.com/orchidsoftware/orchid.software
    about: For documentation issues, open a pull request at the orchidsoftware/orchid.software repository
