name: Tests

on: [push,pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 7.3, 7.2]
        laravel: [7.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 7.*
            testbench: 5.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v1

      - name: Cache dependencies 🔧
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP 🔧
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies 🔧
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests (Unit and Feature tests) via PHPUnit 🧪
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

  dusk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: PHP version
        run: php -v

      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Make SQLite database
        run: vendor/orchestra/testbench-dusk/create-sqlite-db

      - name: Update Dusk Chromedriver
        run: vendor/bin/dusk-updater detect --auto-update

      - name: Execute Unit Tests
        run: vendor/bin/phpunit --testsuite=Browser

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*
